global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
- /etc/prometheus/rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
 
scrape_configs:
  - job_name: 'Prometheus'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:
        - name: tag:Name
          values: [prometheus-server]
    relabel_configs:
      - source_labels: [__meta_ec2_Project, __meta_ec2_tag_Name]
        separator: "_"
        target_label: instance
      - source_labels: [__meta_ec2_private_dns_name]
        target_label: private_dns_name
  - job_name: 'Backend'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:
        - name: tag:Name
          values: [backend-*]
    relabel_configs:
      - source_labels: [__meta_ec2_Project, __meta_ec2_tag_Name]
        separator: "_"
        target_label: instance
      - source_labels: [__meta_ec2_private_dns_name]
        target_label: private_dns_name
